In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import plotly.colors as colors
import warnings
warnings.filterwarnings("ignore")

In [ ]:
data=pd.read_csv("/content/ecom_Superstore.csv",encoding="latin1")

In [ ]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
data.shape

(9994, 21)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [ ]:
data['Order Date']=pd.to_datetime(data['Order Date'])
data['Ship Date']=pd.to_datetime(data['Ship Date'])

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

In [ ]:
data.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [ ]:
data[data.duplicated()]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

In [ ]:
data[data.duplicated()].shape

(0, 21)

In [ ]:
data.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355648,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108

In [ ]:
data['Customer ID'].value_counts()

Customer ID
WB-21850    37
MA-17560    34
JL-15835    34
PP-18955    34
CK-12205    32
            ..
AO-10810     1
LD-16855     1
JR-15700     1
CJ-11875     1
RE-19405     1
Name: count, Length: 793, dtype: int64

In [ ]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
for col in data.columns:
  if data[col].nunique()<=20:
    print(data[col].value_counts())
    print("*"*50)

Ship Mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64
**************************************************
Segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64
**************************************************
Country
United States    9994
Name: count, dtype: int64
**************************************************
Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64
**************************************************
Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64
**************************************************
Sub-Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64
**************************************************
Quantity
3     2409
2     2402
5     1230
4     1191
1      899
7      606
6      572
9      258
8      257
10      57
11      34
14      29
13      27
12      23
Name: count, dtype: int64
**************************************************
Discount
0.00    4798
0.20    3657
0.70     418
0.80     300
0.30     227
0.40     206
0.60     138
0.10      94
0.50      66
0.15      52
0.32      27
0.45      11
Name: count, dtype: int64
**************************************************

In [ ]:
data['Customer ID'].unique()

array(['CG-12520', 'DV-13045', 'SO-20335', 'BH-11710', 'AA-10480',
       'IM-15070', 'HP-14815', 'PK-19075', 'AG-10270', 'ZD-21925',
       'KB-16585', 'SF-20065', 'EB-13870', 'EH-13945', 'TB-21520',
       'MA-17560', 'GH-14485', 'SN-20710', 'LC-16930', 'RA-19885',
       'ES-14080', 'ON-18715', 'PO-18865', 'LH-16900', 'DP-13000',
       'JM-15265', 'TB-21055', 'KM-16720', 'PS-18970', 'BS-11590',
       'KD-16270', 'HM-14980', 'JE-15745', 'KB-16600', 'SC-20770',
       'DN-13690', 'JC-16105', 'CS-12400', 'PG-18895', 'GM-14455',
       'JS-15685', 'KB-16315', 'RB-19705', 'PN-18775', 'KD-16345',
       'ER-13855', 'RB-19465', 'GZ-14470', 'LC-16870', 'JM-15250',
       'PA-19060', 'CV-12805', 'CL-12565', 'RC-19960', 'DK-13090',
       'GG-14650', 'SC-20725', 'AD-10180', 'PF-19165', 'TS-21610',
       'LS-16975', 'DW-13585', 'LC-16885', 'JD-15895', 'SH-19975',
       'SG-20080', 'HA-14920', 'MG-17680', 'JE-16165', 'TW-21025',
       'SP-20650', 'NK-18490', 'DB-13060', 'NP-18670', 'TT-21070',
       'EM-13960', 'RD-19900', 'MJ-17740', 'BM-11140', 'CS-12130',
       'JB-15400', 'SJ-20500', 'JK-15640', 'DK-13150', 'RM-19675',
       'SK-19990', 'FM-14290', 'AM-10360', 'MP-17470', 'MZ-17515',
       'CB-12025', 'VM-21685', 'FH-14365', 'MB-17305', 'BS-11755',
       'LC-17140', 'HK-14890', 'LE-16810', 'JH-15985', 'MS-17980',
       'VW-21775', 'JH-15910', 'JB-15925', 'DS-13180', 'VD-21670',
       'EA-14035', 'DB-13120', 'KL-16645', 'DW-13480', 'LH-17155',
       'KC-16540', 'DL-13315', 'DR-12880', 'CC-12670', 'Dl-13600',
       'SB-20290', 'RC-19825', 'AH-10210', 'CB-12535', 'CA-12310',
       'KH-16690', 'BB-10990', 'AG-10495', 'JO-15280', 'AH-10195',
       'NZ-18565', 'KL-16555', 'AS-10225', 'CR-12625', 'SH-20395',
       'BP-11185', 'TS-21205', 'AG-10525', 'SP-20860', 'NM-18445',
       'FA-14230', 'GK-14620', 'DJ-13510', 'PO-18850', 'JL-15850',
       'DB-13615', 'AC-10420', 'CC-12550', 'TD-20995', 'AB-10060',
       'JL-15505', 'VB-21745', 'KW-16435', 'JD-16060', 'MK-17905',
       'GT-14755', 'AG-10900', 'MM-18280', 'AR-10405', 'RA-19915',
       'AS-10285', 'LA-16780', 'DO-13435', 'DK-13225', 'NG-18430',
       'MV-18190', 'JG-15115', 'BP-11095', 'VP-21730', 'SS-20140',
       'AG-10675', 'LF-17185', 'RF-19840', 'KH-16510', 'KC-16675',
       'CJ-12010', 'PB-19150', 'MP-17965', 'NF-18385', 'SD-20485',
       'KH-16630', 'RB-19795', 'MK-18160', 'PO-19180', 'BB-11545',
       'TB-21595', 'RB-19360', 'EB-13705', 'SC-20095', 'TN-21040',
       'JS-15940', 'MH-17785', 'JP-15520', 'JE-15475', 'JG-15805',
       'XP-21865', 'EM-14065', 'MT-18070', 'SA-20830', 'CW-11905',
       'AJ-10960', 'SS-20590', 'RO-19780', 'MD-17350', 'MY-17380',
       'CM-12385', 'LS-17245', 'BN-11515', 'DB-13210', 'MC-17605',
       'BD-11605', 'PH-18790', 'MG-18145', 'KB-16240', 'JC-15340',
       'RL-19615', 'AA-10375', 'EP-13915', 'DK-12985', 'BD-11500',
       'LM-17065', 'AS-10135', 'BD-11320', 'GT-14710', 'AJ-10945',
       'OT-18730', 'LP-17080', 'CA-12775', 'JF-15490', 'FP-14320',
       'EB-13840', 'JF-15415', 'SF-20200', 'TG-21640', 'CS-11950',
       'CC-12145', 'DV-13465', 'BD-11725', 'ZC-21910', 'MS-17830',
       'LR-16915', 'TP-21130', 'CK-12205', 'AS-10240', 'AR-10510',
       'NB-18655', 'GD-14590', 'CK-12595', 'NG-18355', 'CA-12265',
       'SF-20965', 'MO-17800', 'AT-10735', 'FM-14380', 'DJ-13420',
       'ME-17725', 'JD-16150', 'JL-15835', 'SC-20305', 'CC-12430',
       'AR-10825', 'SR-20740', 'CR-12730', 'EH-14125', 'SP-20545',
       'TH-21235', 'RP-19390', 'RB-19570', 'CD-11980', 'DJ-13630',
       'GT-14635', 'MC-17845', 'RA-19285', 'NP-18325', 'AB-10165',
       'JO-15550', 'JK-15370', 'BN-11470', 'DP-13165', 'TH-21550',
       'AP-10915', 'RS-19765', 'SV-20365', 'CK-12325', 'RD-19810',
       'MR-17545', 'SC-20695', 'JF-15355', 'EG-13900', 'DS-13030',
       'PO-19195', 'SS-20875', 'PB-19105', 'RF-19735', 'YC-21895',
       'DC-13285', 'CP-12340', 'BF-11020', 'LH-17020', 'CS-12250',
       'AJ-10795', 'BV-11245', 'DL-12865', 'BM-11785', 'LT-17110',
       'JK-15730', 'ES-14020', 'RH-19495', 'CD-11920', 'HW-14935',
       'MC-18130', 'GM-14440', 'PJ-19015', 'BW-11110', 'TR-21325',
       'PG-18820', 'JL-15175', 'BM-11650', 'EM-14095', 'AF-10885',
       'GA-14725', 'CK-12760', 'DP-13105', 'BK-11260', 'SJ-20125',
       'CM-12445', 'AJ-10780', 'LS-16945', 'GP-14740', 'PK-18910',
       'SM-20005', 'AG-10765', 'PM-19135', 'LL-16840', 'JS-15595',
       'EL-13735', 'PC-18745', 'HL-15040', 'MS-17365', 'GB-14530',
       'JR-16210', 'BE-11335', 'SC-20050', 'RW-19630', 'SE-20110',
       'AH-10075', 'JM-15535', 'JJ-15760', 'RK-19300', 'CG-12040',
       'RP-19270', 'KC-16255', 'KH-16360', 'GH-14665', 'SW-20275',
       'JA-15970', 'DL-12925', 'LW-16990', 'TB-21190', 'BS-11800',
       'RW-19690', 'TZ-21580', 'AS-10630', 'TS-21340', 'SL-20155',
       'MW-18235', 'RD-19585', 'RA-19945', 'MT-17815', 'VG-21790',
       'JS-15880', 'KM-16225', 'HR-14770', 'DE-13255', 'AG-10390',
       'JJ-15445', 'JH-15430', 'RD-19660', 'MO-17500', 'NS-18640',
       'DG-13300', 'NF-18595', 'MG-17650', 'TS-21160', 'BD-11620',
       'CM-12160', 'SN-20560', 'EH-14005', 'FO-14305', 'MS-17710',
       'CC-12100', 'DW-13540', 'BT-11395', 'CY-12745', 'BT-11485',
       'PS-19045', 'PV-18985', 'NM-18520', 'DL-13495', 'CS-12355',
       'FH-14275', 'NC-18340', 'AA-10315', 'LT-16765', 'AP-10720',
       'PM-18940', 'AT-10435', 'CA-12055', 'HR-14830', 'BT-11530',
       'LH-16750', 'SW-20755', 'SP-20620', 'BF-11170', 'KT-16480',
       'BG-11695', 'GM-14680', 'EJ-14155', 'NP-18700', 'MH-18115',
       'JR-15700', 'SM-20950', 'CC-12220', 'PF-19225', 'DC-12850',
       'BD-11770', 'GM-14500', 'TB-21355', 'JH-16180', 'EB-13975',
       'QJ-19255', 'TC-21535', 'CS-12460', 'HG-14965', 'LW-16825',
       'MC-17575', 'LP-17095', 'EB-14170', 'GZ-14545', 'CP-12085',
       'FG-14260', 'LD-17005', 'AB-10255', 'MN-17935', 'JR-15670',
       'JF-15190', 'CM-12115', 'AS-10045', 'BP-11290', 'ND-18370',
       'LB-16735', 'KT-16465', 'HM-14860', 'AB-10600', 'SZ-20035',
       'MG-17890', 'JK-16120', 'PP-18955', 'YS-21880', 'KM-16375',
       'AB-10105', 'HA-14905', 'BT-11305', 'SV-20815', 'RW-19540',
       'DK-12835', 'ST-20530', 'MM-17920', 'PW-19030', 'SC-20440',
       'TS-21085', 'MC-17425', 'ME-17320', 'NH-18610', 'MB-18085',
       'KD-16495', 'KN-16390', 'NP-18685', 'CS-12505', 'MS-17770',
       'CM-12655', 'Co-12640', 'TS-21370', 'JW-15220', 'JD-15790',
       'PC-19000', 'AR-10540', 'AI-10855', 'TB-21400', 'PL-18925',
       'GH-14425', 'MP-18175', 'JM-15655', 'CL-11890', 'DB-13270',
       'IG-15085', 'BO-11425', 'AB-10150', 'JW-16075', 'EB-13750',
       'SG-20470', 'CM-12190', 'AW-10840', 'MC-18100', 'TT-21460',
       'VG-21805', 'MY-18295', 'RD-19480', 'DP-13390', 'ML-17395',
       'JC-15385', 'JG-15160', 'MC-17275', 'NW-18400', 'TB-21280',
       'BS-11380', 'HH-15010', 'CD-12280', 'TH-21100', 'MM-18055',
       'NS-18505', 'RB-19645', 'SW-20455', 'EB-13930', 'PS-18760',
       'HF-14995', 'HZ-14950', 'CD-12790', 'JK-15205', 'FM-14215',
       'ED-13885', 'DA-13450', 'JW-15955', 'RM-19375', 'ML-17755',
       'CC-12685', 'JE-15610', 'RP-19855', 'TB-21175', 'BE-11455',
       'JF-15565', 'PB-19210', 'BT-11680', 'JL-15235', 'CH-12070',
       'ND-18460', 'BF-10975', 'KH-16330', 'GW-14605', 'NC-18625',
       'ME-18010', 'BP-11230', 'JC-15775', 'AS-10090', 'AC-10450',
       'MD-17860', 'DB-13660', 'EH-13990', 'EH-13765', 'SC-20230',
       'JE-15715', 'AC-10615', 'JD-16015', 'CB-12415', 'JS-16030',
       'LW-17215', 'SC-20800', 'AM-10705', 'RH-19510', 'CT-11995',
       'MC-17590', 'CC-12610', 'KA-16525', 'TC-20980', 'BF-11080',
       'MM-17260', 'AH-10120', 'BW-11200', 'SW-20245', 'BS-11665',
       'RF-19345', 'WB-21850', 'TB-21625', 'AF-10870', 'RB-19435',
       'KF-16285', 'JH-15820', 'IL-15100', 'PB-18805', 'RH-19600',
       'AW-10930', 'ML-17410', 'DB-13555', 'MH-17620', 'DK-13375',
       'BT-11440', 'DB-13405', 'TG-21310', 'BF-11005', 'JM-16195',
       'MZ-17335', 'MW-18220', 'MV-17485', 'SM-20320', 'TP-21415',
       'JK-15625', 'PJ-18835', 'RS-19420', 'SV-20935', 'BC-11125',
       'EM-13825', 'BM-11575', 'KN-16705', 'KW-16570', 'SC-20260',
       'CV-12295', 'SG-20605', 'TM-21010', 'EM-13810', 'ML-18040',
       'CR-12580', 'AZ-10750', 'PW-19240', 'SC-20380', 'CM-11935',
       'GM-14695', 'TB-21250', 'JM-15865', 'SC-20575', 'LS-17200',
       'RR-19315', 'DB-12910', 'TT-21220', 'LO-17170', 'KD-16615',
       'NB-18580', 'BD-11635', 'CM-12235', 'EN-13780', 'KN-16450',
       'BO-11350', 'AG-10300', 'MC-17635', 'TA-21385', 'JF-15295',
       'TT-21265', 'SB-20170', 'CL-12700', 'HG-15025', 'NL-18310',
       'RR-19525', 'TC-21295', 'SV-20785', 'BE-11410', 'SC-20680',
       'DF-13135', 'FH-14350', 'MS-17530', 'RH-19555', 'GA-14515',
       'JP-16135', 'Dp-13240', 'MO-17950', 'DL-13330', 'MH-18025',
       'DR-12940', 'DM-13015', 'CA-11965', 'AC-10660', 'DM-13345',
       'VF-21715', 'CC-12370', 'BF-11275', 'HG-14845', 'BP-11155',
       'EM-14140', 'MA-17995', 'AY-10555', 'GB-14575', 'JB-16045',
       'MG-17875', 'SR-20425', 'JB-16000', 'DM-12955', 'TC-21475',
       'SW-20350', 'RE-19450', 'BF-11215', 'KB-16405', 'JG-15310',
       'EC-14050', 'EB-14110', 'JP-15460', 'CS-11845', 'GH-14410',
       'PT-19090', 'JL-15130', 'AH-10030', 'CC-12475', 'DW-13195',
       'SJ-20215', 'BG-11740', 'LB-16795', 'CM-11815', 'EH-14185',
       'TS-21505', 'PR-18880', 'LC-17050', 'CS-12490', 'DH-13075',
       'JO-15145', 'AH-10690', 'HJ-14875', 'MH-17455', 'RD-19930',
       'SC-20020', 'SU-20665', 'FC-14335', 'RB-19330', 'NC-18535',
       'DB-12970', 'MF-17665', 'RM-19750', 'VM-21835', 'EJ-13720',
       'NC-18415', 'LS-17230', 'KE-16420', 'DH-13675', 'PF-19120',
       'VT-21700', 'MG-17695', 'SP-20920', 'CS-12175', 'DK-12895',
       'KM-16660', 'AA-10645', 'DD-13570', 'AH-10465', 'TP-21565',
       'EK-13795', 'CR-12820', 'SG-20890', 'AH-10585', 'NF-18475',
       'BS-11365', 'SH-20635', 'RD-19720', 'AG-10330', 'GR-14560',
       'VS-21820', 'TM-21490', 'TS-21430', 'DB-13360', 'NR-18550',
       'CS-11860', 'MF-18250', 'LW-17125', 'AR-10345', 'KS-16300',
       'AB-10015', 'LR-17035', 'SS-20410', 'JM-15580', 'JK-15325',
       'DM-13525', 'ML-18265', 'MH-17290', 'FC-14245', 'TH-21115',
       'JK-16090', 'SB-20185', 'BG-11035', 'BW-11065', 'MG-18205',
       'DO-13645', 'BP-11050', 'TS-21655', 'EM-14200', 'AO-10810',
       'MH-17440', 'SS-20515', 'LD-16855', 'VP-21760', 'TC-21145',
       'IM-15055', 'AR-10570', 'CM-12715', 'FW-14395', 'LC-16960',
       'HE-14800', 'BD-11560', 'HD-14785', 'CJ-11875', 'RS-19870',
       'SC-20845', 'RE-19405', 'SM-20905'], dtype=object)

In [ ]:
#Calculating the order_month,order_Year, and Order_Day_Of_week
data['Order_Month']=data['Order Date'].dt.month
data['Order_Year']=data['Order Date'].dt.year
data['Order_Day_Of_Week']=data['Order Date'].dt.dayofweek

In [ ]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
sales_by_month=data.groupby('Order_Month')['Sales'].sum().reset_index()
sales_by_month

    Order_Month        Sales
0             1   94924.8356
1             2   59751.2514
2             3  205005.4888
3             4  137762.1286
4             5  155028.8117
5             6  152718.6793
6             7  147238.0970
7             8  159044.0630
8             9  307649.9457
9            10  200322.9847
10           11  352461.0710
11           12  325293.5035

In [ ]:
fig=px.line(sales_by_month,x='Order_Month',y='Sales',title='Monthly Sales Analysis')
fig.show()
#November month has the highest sales and February month has the lowest sales

In [ ]:
#Sales by Category
sales_by_category=data.groupby('Category')['Sales'].sum().reset_index()
sales_by_category

          Category        Sales
0        Furniture  741999.7953
1  Office Supplies  719047.0320
2       Technology  836154.0330

In [ ]:
fig=px.pie(sales_by_category,values='Sales',names='Category',title='Sales by Category')
fig.show()
# Technology category has the highest sales

In [ ]:
sales_by_subCategory=data.groupby('Sub-Category')['Sales'].sum().reset_index()
sales_by_subCategory

   Sub-Category        Sales
0   Accessories  167380.3180
1    Appliances  107532.1610
2           Art   27118.7920
3       Binders  203412.7330
4     Bookcases  114879.9963
5        Chairs  328449.1030
6       Copiers  149528.0300
7     Envelopes   16476.4020
8     Fasteners    3024.2800
9   Furnishings   91705.1640
10       Labels   12486.3120
11     Machines  189238.6310
12        Paper   78479.2060
13       Phones  330007.0540
14      Storage  223843.6080
15     Supplies   46673.5380
16       Tables  206965.5320

In [ ]:
#plot a graph for this dtaaframe
fig=px.bar(sales_by_subCategory,x='Sub-Category',y='Sales',title='Sales by Sub-Category')
fig.show()

In [ ]:
#profit_by_month
profit_by_month=data.groupby('Order_Month')['Profit'].sum().reset_index()
profit_by_month

    Order_Month      Profit
0             1   9134.4461
1             2  10294.6107
2             3  28594.6872
3             4  11587.4363
4             5  22411.3078
5             6  21285.7954
6             7  13832.6648
7             8  21776.9384
8             9  36857.4753
9            10  31784.0413
10           11  35468.4265
11           12  43369.1919

In [ ]:
fig=px.line(profit_by_month,x='Order_Month',y='Profit',title='Profit by Month',color_discrete_sequence=px.colors.qualitative.Bold)
fig.show()

In [ ]:
profit_by_category=data.groupby('Category')['Profit'].sum().reset_index()
profit_by_category

          Category       Profit
0        Furniture   18451.2728
1  Office Supplies  122490.8008
2       Technology  145454.9481

In [ ]:
fig=px.pie(profit_by_category,values='Profit',names='Category',title='Profit by Category',color_discrete_sequence=px.colors.qualitative.Pastel,hole=0.5)
fig.show()

In [ ]:
#profit_by_sub_category
profit_by_subcategory=data.groupby('Sub-Category')['Profit'].sum().reset_index()
profit_by_subcategory

   Sub-Category      Profit
0   Accessories  41936.6357
1    Appliances  18138.0054
2           Art   6527.7870
3       Binders  30221.7633
4     Bookcases  -3472.5560
5        Chairs  26590.1663
6       Copiers  55617.8249
7     Envelopes   6964.1767
8     Fasteners    949.5182
9   Furnishings  13059.1436
10       Labels   5546.2540
11     Machines   3384.7569
12        Paper  34053.5693
13       Phones  44515.7306
14      Storage  21278.8264
15     Supplies  -1189.0995
16       Tables -17725.4811

In [ ]:
fig=px.bar(profit_by_subcategory,x='Sub-Category',y='Profit',title='Profit by Sub-Category',color_discrete_sequence=px.colors.qualitative.Pastel)
fig.show()
#

In [ ]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order_Month,Order_Year,Order_Day_Of_Week
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,11,2016,1
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,11,2016,1
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,6,2016,6
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,10,2015,6
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,10,2015,6

In [ ]:
#Sales and profit by customer segment
sales_by_customer_segment=data.groupby('Segment').agg({'Sales':'sum','Profit':'sum'}).reset_index()
sales_by_customer_segment

       Segment         Sales       Profit
0     Consumer  1.161401e+06  134119.2092
1    Corporate  7.061464e+05   91979.1340
2  Home Office  4.296531e+05   60298.6785

In [ ]:
fig=go.Figure()
fig.add_trace(go.Bar(x=sales_by_customer_segment['Segment'],y=sales_by_customer_segment['Sales'],name='Sales'))
fig.add_trace(go.Bar(x=sales_by_customer_segment['Segment'],y=sales_by_customer_segment['Profit'],name='Profit'))
fig.update_layout(title='Sales and Profit by Customer Segment',barmode='group')
fig.show()

In [ ]:
sales_by_customer_segment=data.groupby('Segment').agg({'Sales':'sum','Profit':'sum'}).reset_index()
sales_by_customer_segment['Sales_to_profit_Ratio']=sales_by_customer_segment['Sales']/sales_by_customer_segment['Profit']
sales_by_customer_segment

       Segment         Sales       Profit  Sales_to_profit_Ratio
0     Consumer  1.161401e+06  134119.2092               8.659471
1    Corporate  7.061464e+05   91979.1340               7.677245
2  Home Office  4.296531e+05   60298.6785               7.125416

In [ ]:
fig=px.bar(sales_by_customer_segment,x='Segment',y='Sales_to_profit_Ratio',color='Segment',title='Sales to Profit Ratio by Customer Segment')
fig.show()

In [ ]:
data.to_csv('cleaned_superstore_data.csv', index=False)
from google.colab import files
files.download('cleaned_superstore_data.csv')